name: Push to Main
on:
  push:
    branches:
      - main
jobs:
  push:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Lint fix
        run: npm run lint:fix

      - name: Lint application
        run: npm run lint

      - name: Update snapshots
        run: npm run test:u

      - name: Test application
        run: npm run test

      - name: Push to main if tests and lint pass
        if: ${{ success() && steps.test.outcome == 'success' && steps.lint.outcome == 'success' }}
        run: git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
